apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: ctlptl-registry
kindV1Alpha4Cluster:
  name: kind
  networking:
    apiServerAddress: "127.0.0.1"
    apiServerPort: 6443
    podSubnet: "10.240.0.0/16"
    serviceSubnet: "10.0.0.0/16"
    disableDefaultCNI: true
    kubeProxyMode: "iptables"
  nodes:
    - role: control-plane
      extraMounts:
      - hostPath: /run
        containerPath: /eddington/var/run/
      - hostPath: /var/lib/docker
        containerPath: /eddington/var/lib/docker
      kubeadmConfigPatches:
        - |
          kind: InitConfiguration
          nodeRegistration:
            kubeletExtraArgs:
              node-labels: "ingress-ready=true"
      extraPortMappings:
        - containerPort: 30000
          hostPort: 80
          listenAddress: "127.0.0.1"
          protocol: TCP
        - containerPort: 30001
          hostPort: 443
          listenAddress: "127.0.0.1"
          protocol: TCP
        - containerPort: 30002
          hostPort: 15021
          listenAddress: "127.0.0.1"
          protocol: TCP
