apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddington-ui
spec:
  selector:
    matchLabels:
      app: eddington-ui
  template:
    metadata:
      labels:
        app: eddington-ui
    spec:
      containers: 
      - name: eddington-ui
        image: nullchannel/eddington-ui:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000